# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_run', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_to_stop', models.DateTimeField(blank=True, null=True)),
                ('function', picklefield.fields.PickledObjectField(editable=False)),
                ('repeat', models.PositiveIntegerField(default=1)),
                ('every', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
